version: 1
lang: go
name: location-api
contract: 
  config:
    output-grst: grpc2/pb/
    output-scaffold-mysql:  
    output-dependency: grpc/pb-deps/
  proto-files:
    - grpc/proto/province.proto
    - grpc/proto/city.proto

# default examples 
# contract: 
#   config:
#     output-grst: grpc/pb/
#     output-scaffold-mysql:  
#     output-dependency: grpc/pb-deps/
#   proto-files:
#     - grpc/proto/province.proto

# export GO111MODULE=on && export GOPROXY=direct && export GOSUMDB=off && go mod tidy