version: 1
lang: go
name: location-api
contract: 
  proto-files:
    - contract/province.proto
    - contract/city.proto
  config:
    output-grst: drivers/handler/grst/
    output-mysql-model: drivers/datasource/mysql/
    output-dependency: drivers/external/grst/


# default examples 
# contract: 
#   proto-files:
#     - contract/province.proto
#   config:
#     output-grst: drivers/handler/grst/
#     output-mysql-model: drivers/datasource/mysql/
#     output-dependency: drivers/external/grst/

# cdd gen go
# cdd gen go-entity -f city.proto -e "City|CityProfile"
# cdd gen go-entity -f province.proto -e "Province"
