version: 1
lang: go
name: location-api
contract: 
  config:
    output-grst: drivers/handler/grst/
    output-scaffold-mysql:  
    output-dependency: drivers/external/grst/
  proto-files:
    - contract/province.proto
    - contract/city.proto

# default examples 
# contract: 
#   config:
#     output-grst: drivers/handler/grst/
#     output-scaffold-mysql:  
#     output-dependency: drivers/external/grst/
#   proto-files:
#     - contract/province.proto

# export GO111MODULE=on && export GOPROXY=direct && export GOSUMDB=off && go mod tidy