version: 1
lang: go
name: location-api
contract: 
  output-grst: handler/grst/
  proto-files:
    - contract/province.proto
    - contract/city.proto


# default examples 
# contract: 
#   proto-files:
#     - contract/province.proto
#   config:
#     output-grst: drivers/handler/grst/
#     output-mysql-model: drivers/datasource/mysql/
#     output-dependency: drivers/external/grst/

# cdd gen go
# cdd gen go-msq -f repository/city_mysql/model.go -n CityModel
# cdd gen go-msq -f repository/province_mysql/model.go -n ProvinceModel
# cdd gen go-entity -f city.proto -e "City|CityProfile"
# cdd gen go-entity -f province.proto -e "Province"
# all: cdd gen go && cdd gen go-msq -f repository/city_mysql/model.go -n CityModel && cdd gen go-msq -f repository/province_mysql/model.go -n ProvinceModel && cdd gen go-entity -f city.proto -e "City|CityProfile" && cdd gen go-entity -f province.proto -e "Province"
 