version: 1
lang: go
name: users-api
contract: 
  proto-files:
    - contract/users.proto
dependencies:
  services:
    - ../location-api/service.yaml

# default examples 
# contract: 
#   config:
#     output-grst: drivers/handler/grst/
#     output-mysql-model: drivers/datasource/mysql/
#     output-dependency: drivers/external/grst/
#   proto-files:
#     - contract/province.proto

# cdd gen go
# cdd gen go-entity -f users.proto -e "UserProfile|User"
# cdd gen go-ucm -f users.proto -n User
# combine: cdd gen go && cdd gen go-entity -f users.proto -e "UserProfile|User" && cdd gen go-ucm -f users.proto -n User 
 